#!/bin/bash
# Autogenerated health check by Agent Zero

echo "🔍 Validating python-performance-optimization..."

# Check 1: Python availability
if command -v python3 &> /dev/null; then
    echo "✅ Python3 is available."
else
    echo "❌ Python3 not found. Please install python3."
    exit 1
fi

# Check 2: Core dependencies
if python3 -c "import cProfile" 2>/dev/null; then
    echo "✅ cProfile module available."
else
    echo "⚠️  cProfile not available (should be built-in)."
fi

# Check 3: Check for optional profiling tools
if python3 -c "import memory_profiler" 2>/dev/null; then
    echo "✅ memory_profiler available."
else
    echo "ℹ️  memory_profiler not installed (optional)."
fi

if python3 -c "import line_profiler" 2>/dev/null; then
    echo "✅ line_profiler available."
else
    echo "ℹ️  line_profiler not installed (optional)."
fi

# Check 4: Directory structure
if [ -f "SKILL.md" ]; then
    echo "✅ SKILL.md found."
else
    echo "❌ SKILL.md missing."
    exit 1
fi

echo "🚀 python-performance-optimization is ready."
exit 0
