#!/bin/bash
# Autogenerated installation script by Agent Zero

echo "📦 Installing dependencies for async-python-patterns..."

# Check if Python3 is available
if ! command -v python3 &> /dev/null; then
    echo "❌ Python3 not found. Please install Python3 first."
    exit 1
fi

# Check if pip is available
if ! command -v pip3 &> /dev/null; then
    echo "⚠️  pip3 not found. Installing pip..."
    apt-get update && apt-get install -y python3-pip
fi

# Install pytest-asyncio for async testing
pip3 install pytest-asyncio

# Install pytest for testing framework
pip3 install pytest

# Install anyio for async utilities
pip3 install anyio

# Install trio for alternative async framework (optional)
pip3 install trio

# Install uv for faster package management (optional)
pip3 install uv

# Verify installations
echo "✅ Checking installed packages..."
python3 -c "import pytest_asyncio; print(f'pytest-asyncio version: {pytest_asyncio.__version__}')"
python3 -c "import pytest; print(f'pytest version: {pytest.__version__}')"
python3 -c "import anyio; print(f'anyio version: {anyio.__version__}')"

# Create a simple test file to verify async functionality
echo "📝 Creating verification test..."
cat > /tmp/test_async_verification.py << 'EOF'
import asyncio
import pytest

async def simple_coroutine():
    await asyncio.sleep(0.1)
    return "async test passed"

@pytest.mark.asyncio
async def test_simple_coroutine():
    result = await simple_coroutine()
    assert result == "async test passed"
    print(f"Test result: {result}")

if __name__ == "__main__":
    # Run the coroutine directly
    result = asyncio.run(simple_coroutine())
    print(f"Direct execution: {result}")

    # Run pytest test
    import sys
    sys.exit(pytest.main([__file__, "-v"]))
EOF

# Run the verification test
echo "🔧 Running verification test..."
cd /tmp && python3 test_async_verification.py

if [ $? -eq 0 ]; then
    echo "✅ async-python-patterns dependencies installed successfully."
else
    echo "⚠️  Some tests failed, but installation completed."
fi

echo "🚀 Installation complete. Run 'bash test.sh' to verify the skill."
