#!/bin/bash
# Autogenerated health check by Agent Zero

echo "🔍 Validating async-python-patterns..."

# Check 1: Python3 availability
if command -v python3 &> /dev/null; then
    echo "✅ Python3 is available."
else
    echo "❌ Python3 not found. Please install Python3."
    exit 1
fi

# Check 2: asyncio module
python3 -c "import asyncio" 2>/dev/null
if [ $? -eq 0 ]; then
    echo "✅ asyncio module available."
else
    echo "❌ asyncio module not found. This is a standard Python library."
    exit 1
fi

# Check 3: pytest-asyncio (optional but recommended)
python3 -c "import pytest_asyncio" 2>/dev/null
if [ $? -eq 0 ]; then
    echo "✅ pytest-asyncio is available."
else
    echo "ℹ️  pytest-asyncio not installed (optional)."
fi

# Check 4: SKILL.md exists
if [ -f "SKILL.md" ]; then
    echo "✅ SKILL.md found."
else
    echo "❌ SKILL.md not found."
    exit 1
fi

# Simple async test
python3 -c "
import asyncio

async def test_coroutine():
    return 'test passed'

async def main():
    result = await test_coroutine()
    print(f'Simple async test: {result}')

asyncio.run(main())
"

if [ $? -eq 0 ]; then
    echo "✅ Basic async execution works."
else
    echo "❌ Basic async test failed."
    exit 1
fi

echo "🚀 async-python-patterns is ready."
exit 0
