#!/bin/bash
# Autogenerated installation script by Agent Zero

echo "🔧 Installing dependencies for rust-async-patterns..."

# Check if Rust is already installed
if command -v rustc &> /dev/null && command -v cargo &> /dev/null; then
    echo "✅ Rust is already installed"
    echo "rustc: $(rustc --version)"
    echo "cargo: $(cargo --version)"
    exit 0
fi

echo "📦 Installing Rust via rustup..."

# Install rustup (Rust toolchain installer)
if ! command -v curl &> /dev/null; then
    echo "❌ curl is required but not installed. Installing curl..."
    apt-get update && apt-get install -y curl
fi

# Download and run rustup installer
echo "Downloading rustup installer..."
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Add cargo to PATH
if [ -f "$HOME/.cargo/env" ]; then
    source "$HOME/.cargo/env"
    echo "✅ Rust installed successfully"
    echo "rustc: $(rustc --version)"
    echo "cargo: $(cargo --version)"
else
    echo "⚠️  Rust installation may have completed but .cargo/env not found"
    echo "Please restart your shell or run: source $HOME/.cargo/env"
fi

echo "🚀 Rust installation complete. You can now use rust-async-patterns skill."
