#!/bin/bash
# Autogenerated health check by Agent Zero

echo "🔍 Validating rust-async-patterns..."

# Check 1: Rust compiler
if command -v rustc &> /dev/null; then
    echo "✅ rustc found: $(rustc --version)"
else
    echo "❌ rustc not found. Install with: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
    exit 1
fi

# Check 2: Cargo package manager
if command -v cargo &> /dev/null; then
    echo "✅ cargo found: $(cargo --version)"
else
    echo "❌ cargo not found. Install with Rust installation above."
    exit 1
fi

echo "🚀 rust-async-patterns is ready."
exit 0
