#!/bin/bash
# Autogenerated health check by Agent Zero

echo "🔍 Validating monorepo-management..."

# Check 1: Node.js
if command -v node &> /dev/null; then
    echo "✅ Node.js is installed: $(node --version)"
else
    echo "⚠️  Node.js is not installed. This skill requires Node.js for monorepo tools."
fi

# Check 2: npm
if command -v npm &> /dev/null; then
    echo "✅ npm is installed: $(npm --version)"
else
    echo "⚠️  npm is not installed. Install with: apt-get install npm"
fi

# Check 3: Git
if command -v git &> /dev/null; then
    echo "✅ Git is installed: $(git --version | head -1)"
else
    echo "⚠️  Git is not installed. Install with: apt-get install git"
fi

# Check 4: SKILL.md exists
if [ -f "SKILL.md" ]; then
    echo "✅ SKILL.md found."
else
    echo "❌ SKILL.md not found!"
    exit 1
fi

echo "🚀 monorepo-management is ready."
exit 0
