#!/bin/bash
# Autogenerated installation script by Agent Zero

echo "📦 Installing dependencies for python-testing-patterns..."

# Check if pip is available
if command -v pip3 &> /dev/null; then
    echo "✅ pip3 is available."
    PIP_CMD="pip3"
elif command -v pip &> /dev/null; then
    echo "✅ pip is available."
    PIP_CMD="pip"
else
    echo "❌ pip not found. Installing pip..."
    apt-get update && apt-get install -y python3-pip
    PIP_CMD="pip3"
fi

# Install pytest
if ! python3 -m pytest --version &> /dev/null; then
    echo "Installing pytest..."
    $PIP_CMD install pytest
else
    echo "✅ pytest already installed."
fi

# Install pytest plugins and common testing libraries
echo "Installing pytest plugins and testing libraries..."
$PIP_CMD install pytest-cov pytest-mock pytest-xdist pytest-asyncio pytest-html

# Install mock library (for Python < 3.3)
if python3 -c "import sys; sys.exit(0 if sys.version_info >= (3,3) else 1)"; then
    echo "✅ Python 3.3+ has unittest.mock built-in."
else
    echo "Installing mock library for older Python..."
    $PIP_CMD install mock
fi

# Install hypothesis for property-based testing
$PIP_CMD install hypothesis

# Install factory_boy for test data factories
$PIP_CMD install factory_boy

# Install freezegun for time mocking
$PIP_CMD install freezegun

# Install responses for HTTP mocking
$PIP_CMD install responses

# Install parameterized for parameterized tests
$PIP_CMD install parameterized

echo "✅ All dependencies installed for python-testing-patterns."
echo ""
echo "To verify installation, run:"
echo "  bash ~/.gemini/skills/python-testing-patterns/test.sh"
