#!/bin/bash
# Autogenerated health check by Agent Zero

echo "🔍 Validating python-testing-patterns..."

# Check 1: Python availability
if command -v python3 &> /dev/null; then
    echo "✅ Python3 is available."
else
    echo "❌ Python3 not found. Please install python3."
    exit 1
fi

# Check 2: pytest availability
if python3 -m pytest --version &> /dev/null; then
    echo "✅ pytest is available."
else
    echo "❌ pytest not found. Please install pytest."
    exit 1
fi

# Check 3: Check for common testing libraries
if python3 -c "import unittest" 2>/dev/null; then
    echo "✅ unittest module available."
else
    echo "⚠️  unittest not available (should be built-in)."
fi

if python3 -c "import mock" 2>/dev/null; then
    echo "✅ mock library available."
else
    echo "ℹ️  mock not installed (optional)."
fi

# Check 4: Directory structure
if [ -f "SKILL.md" ]; then
    echo "✅ SKILL.md found."
else
    echo "❌ SKILL.md missing."
    exit 1
fi

# Check 5: Create a simple test to verify pytest works
echo ""
echo "Running a simple pytest verification..."
cat > /tmp/test_verification.py << 'PYEOF'
def test_verification():
    assert 1 + 1 == 2

if __name__ == "__main__":
    test_verification()
    print("Simple test passed!")
PYEOF

if python3 /tmp/test_verification.py; then
    echo "✅ Basic Python test execution works."
else
    echo "⚠️  Basic Python test execution failed."
fi

rm -f /tmp/test_verification.py

echo "🚀 python-testing-patterns is ready."
exit 0
