#!/bin/bash
# Autogenerated installation script by Agent Zero

echo "📦 Installing git-commit-formatter dependencies..."

# Check if git is installed
if command -v git &> /dev/null; then
    echo "✅ Git is already installed."
else
    echo "❌ Git is not installed. Please install git:"
    echo "   Ubuntu/Debian: sudo apt-get install git"
    echo "   macOS: brew install git"
    echo "   Windows: Download from https://git-scm.com/"
    exit 1
fi

# Check git configuration
if ! git config --get user.name &> /dev/null; then
    echo "⚠️  Git user.name is not configured. Run:"
    echo "   git config --global user.name 'Your Name'"
fi

if ! git config --get user.email &> /dev/null; then
    echo "⚠️  Git user.email is not configured. Run:"
    echo "   git config --global user.email 'your.email@example.com'"
fi

echo "🚀 git-commit-formatter installation complete."
exit 0
