#!/bin/bash
# Autogenerated health check by Agent Zero

echo "🔍 Validating git-commit-formatter..."

# Check 1: Git installation
if command -v git &> /dev/null; then
    echo "✅ Git is installed."
else
    echo "❌ Git is not installed. Please install git first."
    exit 1
fi

# Check 2: Git configuration
if git config --get user.name &> /dev/null && git config --get user.email &> /dev/null; then
    echo "✅ Git user configuration is set."
else
    echo "⚠️  Git user configuration is not set. Run:"
    echo "   git config --global user.name 'Your Name'"
    echo "   git config --global user.email 'your.email@example.com'"
fi

echo "🚀 git-commit-formatter is ready."
exit 0
