import type { ToolEntity, ModelEntity, AgentEntity, SkillEntity, ScriptEntity, BenchmarkEntity, Entity } from "../lib/types";

// ─── Tools ───────────────────────────────────────────────────────────

const pinecone: ToolEntity = {
  slug: "pinecone",
  type: "tool",
  name: "Pinecone",
  category: "ai-tools",
  tags: ["vector-database", "embeddings", "similarity-search", "serverless", "rag"],
  description: "Purpose-built vector database for high-performance similarity search at any scale. Offers serverless and pod-based deployment with integrated sparse-dense indexing for hybrid search.",
  provider: "Pinecone Systems",
  version: "3.0",
  pricingModel: "freemium",
  license: "Proprietary",
  url: "https://www.pinecone.io",
  apiAvailable: true,
  apiDocsUrl: "https://docs.pinecone.io/reference/api/introduction",
  capabilities: ["vector-search", "hybrid-search", "metadata-filtering", "namespace-isolation", "sparse-dense-indexing"],
  integrations: ["langchain", "llama-index", "haystack", "openai", "cohere", "aws-bedrock"],
  useCases: ["semantic-search", "recommendation-systems", "rag-retrieval", "anomaly-detection", "image-similarity"],
  relatedTools: ["langchain", "cursor"],
  relatedModels: ["claude-4", "gpt-5"],
  relatedAgents: [],
  relatedSkills: ["rag-retrieval"],
  scores: { adoption: 88, quality: 90, freshness: 85, citations: 78, engagement: 0, composite: 79.7 },
  schemaCompleteness: 100,
  lastVerified: "2026-03-01",
  lastUpdated: "2026-03-01",
  addedDate: "2026-03-10",
  addedBy: "system",
  sdkLanguages: ["python", "typescript", "java", "go"],
  deploymentOptions: ["serverless", "pod-based", "enterprise-dedicated"],
  rateLimits: "100 reads/sec on free tier; custom on paid plans",
  dataPrivacy: "SOC 2 Type II, GDPR compliant, data encrypted at rest and in transit",
};

const langchain: ToolEntity = {
  slug: "langchain",
  type: "tool",
  name: "LangChain",
  category: "ai-tools",
  tags: ["llm-framework", "chains", "agents", "rag", "orchestration"],
  description: "Open-source framework for building applications powered by language models. Provides modular abstractions for chains, agents, retrieval, and memory with extensive integrations.",
  provider: "LangChain Inc.",
  version: "0.3.14",
  pricingModel: "open-source",
  license: "MIT",
  url: "https://langchain.com",
  apiAvailable: true,
  apiDocsUrl: "https://python.langchain.com/docs/",
  capabilities: ["chain-composition", "agent-orchestration", "rag-pipelines", "tool-use", "memory-management", "streaming"],
  integrations: ["openai", "anthropic", "pinecone", "chroma", "weaviate", "huggingface", "aws-bedrock"],
  useCases: ["chatbots", "document-qa", "data-extraction", "code-analysis", "multi-agent-workflows"],
  relatedTools: ["pinecone", "cursor"],
  relatedModels: ["claude-4", "gpt-5"],
  relatedAgents: ["claude-code", "devin"],
  relatedSkills: ["rag-retrieval"],
  scores: { adoption: 92, quality: 82, freshness: 90, citations: 88, engagement: 0, composite: 82.4 },
  schemaCompleteness: 100,
  lastVerified: "2026-03-01",
  lastUpdated: "2026-03-05",
  addedDate: "2026-03-10",
  addedBy: "system",
  sdkLanguages: ["python", "typescript"],
  deploymentOptions: ["self-hosted", "langsmith-cloud"],
  rateLimits: "N/A (open-source, depends on underlying providers)",
  dataPrivacy: "Self-hosted by default; LangSmith cloud is SOC 2 Type II compliant",
};

const cursor: ToolEntity = {
  slug: "cursor",
  type: "tool",
  name: "Cursor",
  category: "ai-code",
  tags: ["ai-ide", "code-editor", "copilot", "code-generation", "refactoring"],
  description: "AI-first code editor built on VS Code with deep language model integration for code generation, editing, and understanding. Features tab completion, inline chat, and multi-file editing.",
  provider: "Anysphere",
  version: "0.48",
  pricingModel: "freemium",
  license: "Proprietary",
  url: "https://cursor.com",
  apiAvailable: false,
  apiDocsUrl: "",
  capabilities: ["code-generation", "code-editing", "codebase-search", "multi-file-editing", "tab-completion", "inline-chat"],
  integrations: ["vscode-extensions", "github", "gitlab", "anthropic", "openai"],
  useCases: ["rapid-prototyping", "code-refactoring", "bug-fixing", "learning-new-codebases", "pair-programming"],
  relatedTools: ["langchain"],
  relatedModels: ["claude-4", "gpt-5"],
  relatedAgents: ["claude-code", "devin"],
  relatedSkills: [],
  scores: { adoption: 85, quality: 88, freshness: 92, citations: 72, engagement: 0, composite: 75.6 },
  schemaCompleteness: 95,
  lastVerified: "2026-03-01",
  lastUpdated: "2026-03-08",
  addedDate: "2026-03-10",
  addedBy: "system",
  sdkLanguages: [],
  deploymentOptions: ["desktop-app"],
  rateLimits: "500 premium requests/month on Pro plan",
  dataPrivacy: "Privacy mode available; code not stored when enabled",
};

// ─── Models ──────────────────────────────────────────────────────────

const claude4: ModelEntity = {
  slug: "claude-4",
  type: "model",
  name: "Claude 4",
  category: "llms",
  tags: ["llm", "reasoning", "coding", "multimodal", "long-context"],
  description: "Anthropic's most capable model featuring advanced reasoning, coding, and multimodal capabilities. Excels at complex analysis, agentic tasks, and extended thinking with industry-leading safety.",
  provider: "Anthropic",
  version: "claude-4-20260301",
  pricingModel: "paid",
  license: "Proprietary",
  url: "https://anthropic.com/claude",
  apiAvailable: true,
  apiDocsUrl: "https://docs.anthropic.com/en/docs/about-claude/models",
  capabilities: ["text-generation", "code-generation", "multimodal-vision", "extended-thinking", "tool-use", "agentic-tasks"],
  integrations: ["aws-bedrock", "google-cloud-vertex", "langchain", "llama-index"],
  useCases: ["code-generation", "document-analysis", "research", "agentic-workflows", "content-creation"],
  relatedTools: ["langchain", "cursor", "pinecone"],
  relatedModels: ["gpt-5"],
  relatedAgents: ["claude-code"],
  relatedSkills: ["rag-retrieval"],
  scores: { adoption: 90, quality: 95, freshness: 98, citations: 92, engagement: 0, composite: 85.0 },
  schemaCompleteness: 100,
  lastVerified: "2026-03-01",
  lastUpdated: "2026-03-01",
  addedDate: "2026-03-10",
  addedBy: "system",
  parameterCount: "Undisclosed",
  contextWindow: "200K tokens",
  modalities: ["text", "image", "pdf"],
  trainingDataCutoff: "Early 2026",
  benchmarkScores: { "MMLU": 92.3, "HumanEval": 94.1, "GPQA-Diamond": 78.5, "SWE-bench-Verified": 72.7 },
};

const gpt5: ModelEntity = {
  slug: "gpt-5",
  type: "model",
  name: "GPT-5",
  category: "llms",
  tags: ["llm", "reasoning", "multimodal", "function-calling", "agents"],
  description: "OpenAI's frontier model with advanced reasoning, native multimodal understanding, and robust function calling. Designed for complex enterprise workflows and agentic applications.",
  provider: "OpenAI",
  version: "gpt-5-20260215",
  pricingModel: "paid",
  license: "Proprietary",
  url: "https://openai.com/gpt-5",
  apiAvailable: true,
  apiDocsUrl: "https://platform.openai.com/docs/models/gpt-5",
  capabilities: ["text-generation", "code-generation", "multimodal-vision", "function-calling", "structured-output", "reasoning"],
  integrations: ["azure-openai", "langchain", "llama-index", "semantic-kernel"],
  useCases: ["enterprise-automation", "code-generation", "data-analysis", "content-creation", "customer-support"],
  relatedTools: ["langchain", "cursor", "pinecone"],
  relatedModels: ["claude-4"],
  relatedAgents: ["devin"],
  relatedSkills: ["rag-retrieval"],
  scores: { adoption: 94, quality: 93, freshness: 95, citations: 90, engagement: 0, composite: 86.7 },
  schemaCompleteness: 100,
  lastVerified: "2026-03-01",
  lastUpdated: "2026-02-20",
  addedDate: "2026-03-10",
  addedBy: "system",
  parameterCount: "Undisclosed",
  contextWindow: "256K tokens",
  modalities: ["text", "image", "audio", "video"],
  trainingDataCutoff: "Late 2025",
  benchmarkScores: { "MMLU": 91.8, "HumanEval": 92.5, "GPQA-Diamond": 76.2, "SWE-bench-Verified": 68.4 },
};

// ─── Agents ──────────────────────────────────────────────────────────

const claudeCode: AgentEntity = {
  slug: "claude-code",
  type: "agent",
  name: "Claude Code",
  category: "ai-code",
  tags: ["coding-agent", "cli", "agentic", "autonomous", "developer-tools"],
  description: "Anthropic's agentic coding tool that lives in the terminal. Understands entire codebases, edits files, runs commands, and manages git workflows autonomously with minimal supervision.",
  provider: "Anthropic",
  version: "1.0",
  pricingModel: "paid",
  license: "Proprietary",
  url: "https://docs.anthropic.com/en/docs/agents-and-tools/claude-code",
  apiAvailable: false,
  apiDocsUrl: "",
  capabilities: ["code-editing", "file-management", "git-operations", "command-execution", "codebase-search", "multi-file-refactoring"],
  integrations: ["github", "gitlab", "vscode", "terminal"],
  useCases: ["feature-development", "bug-fixing", "code-refactoring", "test-writing", "ci-cd-debugging"],
  relatedTools: ["cursor", "langchain"],
  relatedModels: ["claude-4"],
  relatedAgents: ["devin"],
  relatedSkills: [],
  scores: { adoption: 78, quality: 92, freshness: 96, citations: 70, engagement: 0, composite: 72.1 },
  schemaCompleteness: 95,
  lastVerified: "2026-03-01",
  lastUpdated: "2026-03-08",
  addedDate: "2026-03-10",
  addedBy: "system",
  autonomyLevel: "semi-autonomous",
  toolsUsed: ["bash", "file-editor", "grep", "git"],
  skills: ["code-generation", "debugging", "refactoring", "testing"],
  trustScore: 88,
  contributionCount: 0,
};

const devin: AgentEntity = {
  slug: "devin",
  type: "agent",
  name: "Devin",
  category: "ai-code",
  tags: ["coding-agent", "autonomous", "full-stack", "software-engineer"],
  description: "Cognition's fully autonomous AI software engineer capable of planning, coding, debugging, and deploying entire features. Operates in a sandboxed environment with its own browser, editor, and terminal.",
  provider: "Cognition",
  version: "2.0",
  pricingModel: "paid",
  license: "Proprietary",
  url: "https://devin.ai",
  apiAvailable: true,
  apiDocsUrl: "https://docs.devin.ai/api",
  capabilities: ["autonomous-coding", "planning", "debugging", "deployment", "browser-interaction", "test-writing"],
  integrations: ["github", "slack", "jira", "linear"],
  useCases: ["feature-development", "bug-triage", "codebase-migration", "proof-of-concepts", "automated-testing"],
  relatedTools: ["cursor", "langchain"],
  relatedModels: ["gpt-5"],
  relatedAgents: ["claude-code"],
  relatedSkills: [],
  scores: { adoption: 72, quality: 80, freshness: 88, citations: 82, engagement: 0, composite: 71.3 },
  schemaCompleteness: 100,
  lastVerified: "2026-03-01",
  lastUpdated: "2026-02-25",
  addedDate: "2026-03-10",
  addedBy: "system",
  autonomyLevel: "fully-autonomous",
  toolsUsed: ["browser", "terminal", "code-editor", "git"],
  skills: ["full-stack-development", "debugging", "deployment", "testing"],
  trustScore: 75,
  contributionCount: 0,
};

// ─── Skills ──────────────────────────────────────────────────────────

const ragRetrieval: SkillEntity = {
  slug: "rag-retrieval",
  type: "skill",
  name: "RAG Retrieval",
  category: "llms",
  tags: ["rag", "retrieval", "embeddings", "vector-search", "knowledge-base"],
  description: "Retrieval-augmented generation skill enabling agents to query external knowledge bases via vector similarity search, reranking, and context injection for grounded, accurate responses.",
  provider: "AaaS",
  version: "1.0",
  pricingModel: "open-source",
  license: "MIT",
  url: "https://aaas.superforge.io/skills/rag-retrieval",
  apiAvailable: false,
  apiDocsUrl: "",
  capabilities: ["vector-retrieval", "semantic-search", "context-injection", "document-chunking", "reranking"],
  integrations: ["pinecone", "chroma", "weaviate", "langchain", "llama-index"],
  useCases: ["document-qa", "knowledge-base-search", "customer-support", "research-assistant"],
  relatedTools: ["pinecone", "langchain"],
  relatedModels: ["claude-4", "gpt-5"],
  relatedAgents: [],
  relatedSkills: ["web-scraping"],
  scores: { adoption: 82, quality: 85, freshness: 80, citations: 74, engagement: 0, composite: 74.3 },
  schemaCompleteness: 100,
  lastVerified: "2026-03-01",
  lastUpdated: "2026-03-01",
  addedDate: "2026-03-10",
  addedBy: "system",
  supportedAgents: ["claude-code", "devin"],
  difficulty: "intermediate",
  prerequisites: ["embeddings-fundamentals", "vector-databases"],
  implementationGuideUrl: "https://aaas.superforge.io/guides/rag-retrieval",
};

const webScraping: SkillEntity = {
  slug: "web-scraping",
  type: "skill",
  name: "Web Scraping",
  category: "ai-tools",
  tags: ["scraping", "web-data", "extraction", "crawling", "automation"],
  description: "Structured web data extraction skill for agents. Enables crawling, parsing, and transforming web content into structured formats for downstream processing and analysis.",
  provider: "AaaS",
  version: "1.0",
  pricingModel: "open-source",
  license: "MIT",
  url: "https://aaas.superforge.io/skills/web-scraping",
  apiAvailable: false,
  apiDocsUrl: "",
  capabilities: ["html-parsing", "dynamic-rendering", "data-extraction", "rate-limiting", "proxy-rotation"],
  integrations: ["playwright", "puppeteer", "cheerio", "beautiful-soup"],
  useCases: ["market-research", "competitive-analysis", "data-aggregation", "content-monitoring"],
  relatedTools: ["langchain"],
  relatedModels: [],
  relatedAgents: ["devin"],
  relatedSkills: ["rag-retrieval"],
  scores: { adoption: 70, quality: 78, freshness: 75, citations: 60, engagement: 0, composite: 63.6 },
  schemaCompleteness: 100,
  lastVerified: "2026-03-01",
  lastUpdated: "2026-03-01",
  addedDate: "2026-03-10",
  addedBy: "system",
  supportedAgents: ["devin"],
  difficulty: "beginner",
  prerequisites: ["html-css-basics"],
  implementationGuideUrl: "https://aaas.superforge.io/guides/web-scraping",
};

// ─── Scripts ─────────────────────────────────────────────────────────

const ragPipelineSetup: ScriptEntity = {
  slug: "rag-pipeline-setup",
  type: "script",
  name: "RAG Pipeline Setup",
  category: "ai-infrastructure",
  tags: ["rag", "pipeline", "setup", "infrastructure", "automation"],
  description: "End-to-end setup script for deploying a production RAG pipeline. Provisions vector database, configures document ingestion, sets up embedding generation, and creates retrieval endpoints.",
  provider: "AaaS",
  version: "1.2",
  pricingModel: "open-source",
  license: "MIT",
  url: "https://github.com/superforge/aaas-scripts/tree/main/rag-pipeline-setup",
  apiAvailable: false,
  apiDocsUrl: "",
  capabilities: ["vector-db-provisioning", "document-ingestion", "embedding-generation", "endpoint-creation", "monitoring-setup"],
  integrations: ["pinecone", "openai", "langchain", "docker", "terraform"],
  useCases: ["rag-deployment", "knowledge-base-setup", "enterprise-search", "document-processing"],
  relatedTools: ["pinecone", "langchain"],
  relatedModels: ["claude-4", "gpt-5"],
  relatedAgents: [],
  relatedSkills: ["rag-retrieval"],
  scores: { adoption: 65, quality: 80, freshness: 82, citations: 55, engagement: 0, composite: 60.75 },
  schemaCompleteness: 100,
  lastVerified: "2026-03-01",
  lastUpdated: "2026-02-15",
  addedDate: "2026-03-10",
  addedBy: "system",
  language: "python",
  dependencies: ["pinecone-client", "langchain", "openai", "tiktoken", "docker"],
  executionEnvironment: "Python 3.11+ with Docker",
  estimatedRuntime: "5-15 minutes depending on document corpus size",
};

// ─── Benchmarks ──────────────────────────────────────────────────────

const sweBench: BenchmarkEntity = {
  slug: "swe-bench",
  type: "benchmark",
  name: "SWE-bench",
  category: "ai-code",
  tags: ["benchmark", "coding", "software-engineering", "evaluation", "agents"],
  description: "Benchmark for evaluating LLMs and AI agents on real-world software engineering tasks drawn from GitHub issues. Tests the ability to understand codebases, diagnose bugs, and produce working patches.",
  provider: "Princeton NLP",
  version: "Verified 1.0",
  pricingModel: "open-source",
  license: "MIT",
  url: "https://www.swebench.com",
  apiAvailable: false,
  apiDocsUrl: "",
  capabilities: ["model-evaluation", "agent-evaluation", "code-generation-testing", "regression-testing"],
  integrations: ["github", "docker"],
  useCases: ["model-comparison", "agent-benchmarking", "coding-ability-assessment", "research"],
  relatedTools: ["langchain"],
  relatedModels: ["claude-4", "gpt-5"],
  relatedAgents: ["claude-code", "devin"],
  relatedSkills: [],
  scores: { adoption: 88, quality: 92, freshness: 90, citations: 95, engagement: 0, composite: 82.55 },
  schemaCompleteness: 100,
  lastVerified: "2026-03-01",
  lastUpdated: "2026-02-28",
  addedDate: "2026-03-10",
  addedBy: "system",
  evaluatedModels: ["claude-4", "gpt-5", "gemini-2.5-pro", "deepseek-v3"],
  metrics: ["resolve-rate", "pass@1", "patch-accuracy"],
  methodology: "Real GitHub issues with validated test patches. Models must produce code patches that pass repository test suites in isolated Docker environments.",
  lastRunDate: "2026-02-28",
  resultsTable: {
    "claude-4": { "resolve-rate": 72.7, "pass@1": 68.3 },
    "gpt-5": { "resolve-rate": 68.4, "pass@1": 64.1 },
    "gemini-2.5-pro": { "resolve-rate": 63.8, "pass@1": 59.2 },
    "deepseek-v3": { "resolve-rate": 55.2, "pass@1": 51.0 },
  },
};

// ─── Export ──────────────────────────────────────────────────────────

export const seedEntities: Entity[] = [
  pinecone,
  langchain,
  cursor,
  claude4,
  gpt5,
  claudeCode,
  devin,
  ragRetrieval,
  webScraping,
  ragPipelineSetup,
  sweBench,
];
