#!/bin/bash
# Autogenerated health check by Agent Zero

echo "🔍 Validating airflow-dag-patterns..."

# Check 1: Python availability
if command -v python3 &> /dev/null; then
    echo "✅ Python3 is available."
else
    echo "❌ Python3 not found. This skill requires Python 3."
    exit 1
fi

# Check 2: Apache Airflow availability
if python3 -c "import airflow" 2>/dev/null; then
    echo "✅ Apache Airflow is available."
else
    echo "⚠️  Apache Airflow is not installed. This skill requires Airflow for full functionality."
    echo "   You can install it with: pip install apache-airflow"
fi

# Check 3: Directory integrity
if [ -f "SKILL.md" ]; then
    echo "✅ SKILL.md found."
else
    echo "❌ SKILL.md not found in skill directory."
    exit 1
fi

echo "🚀 airflow-dag-patterns is ready."
exit 0
