#!/bin/bash
# Autogenerated health check by Agent Zero

echo "🔍 Validating api-testing-observability skill..."

# Check 1: Core dependencies
echo "\n📦 Checking core dependencies:"

# Python
if command -v python3 &> /dev/null; then
    python_version=$(python3 --version 2>&1 | cut -d' ' -f2)
    echo "✅ Python $python_version installed"
else
    echo "❌ Python 3 not found"
    exit 1
fi

# FastAPI check (via pip)
if python3 -c "import fastapi" 2>/dev/null; then
    echo "✅ FastAPI available"
else
    echo "⚠️  FastAPI not installed (will be installed with install.sh)"
fi

# Uvicorn check
if python3 -c "import uvicorn" 2>/dev/null; then
    echo "✅ Uvicorn available"
else
    echo "⚠️  Uvicorn not installed (will be installed with install.sh)"
fi

# Pydantic check
if python3 -c "import pydantic" 2>/dev/null; then
    echo "✅ Pydantic available"
else
    echo "⚠️  Pydantic not installed (will be installed with install.sh)"
fi

# Requests check
if python3 -c "import requests" 2>/dev/null; then
    echo "✅ Requests available"
else
    echo "⚠️  Requests not installed (will be installed with install.sh)"
fi

# Check 2: Skill structure
echo "\n📁 Checking skill structure:"
if [ -f "SKILL.md" ]; then
    echo "✅ SKILL.md found"
    
    # Check YAML frontmatter
    if head -20 SKILL.md | grep -q "^---"; then
        echo "✅ YAML frontmatter present"
    else
        echo "⚠️  YAML frontmatter missing or malformed"
    fi
else
    echo "❌ SKILL.md not found"
    exit 1
fi

if [ -f "test.sh" ]; then
    echo "✅ test.sh found (this file)"
else
    echo "❌ test.sh not found"
    exit 1
fi

if [ -f "install.sh" ]; then
    echo "✅ install.sh found"
else
    echo "⚠️  install.sh not found (optional but recommended)"
fi

# Check 3: Optional directories
echo "\n🎨 Checking optional directories:"
if [ -d "templates" ]; then
    echo "✅ templates/ directory found"
else
    echo "ℹ️  templates/ directory not found (can be created later)"
fi

if [ -d "scripts" ]; then
    echo "✅ scripts/ directory found"
else
    echo "ℹ️  scripts/ directory not found (can be created later)"
fi

echo "\n🚀 API testing & observability skill is ready for use!"
echo "\n📋 Next steps:"
echo "1. Review SKILL.md for API mocking and documentation capabilities"
echo "2. Run install.sh to install any missing dependencies"
echo "3. Use the skill to create mock APIs or generate documentation"

exit 0
