#!/bin/bash
# Autogenerated health check by Agent Zero

echo "🔍 Validating sql-optimization-patterns..."

# Check 1: Core dependencies
if command -v sqlite3 &> /dev/null; then
    echo "✅ SQLite3 is available."
else
    echo "⚠️  SQLite3 is not installed. This skill can use SQLite for testing."
fi

if command -v psql &> /dev/null; then
    echo "✅ PostgreSQL client is available."
else
    echo "⚠️  PostgreSQL client (psql) is not installed. Install with: apt-get install postgresql-client"
fi

if command -v mysql &> /dev/null; then
    echo "✅ MySQL client is available."
else
    echo "⚠️  MySQL client is not installed. Install with: apt-get install mysql-client"
fi

# Check 2: Skill file
if [ -f "SKILL.md" ]; then
    echo "✅ SKILL.md found."
else
    echo "❌ SKILL.md missing!"
    exit 1
fi

echo "🚀 sql-optimization-patterns is ready."
exit 0
