#!/bin/bash
# Autogenerated health check by Agent Zero

echo "🔍 Validating dbt-transformation-patterns..."

# Check 1: Python availability
if command -v python3 &> /dev/null; then
    echo "✅ Python3 is available."
else
    echo "❌ Python3 not found. This skill requires Python 3."
    exit 1
fi

# Check 2: dbt availability
if command -v dbt &> /dev/null; then
    echo "✅ dbt is available."
    dbt --version
else
    echo "⚠️  dbt is not installed. This skill requires dbt for full functionality."
    echo "   You can install it with: pip install dbt-core"
fi

# Check 3: Directory integrity
if [ -f "SKILL.md" ]; then
    echo "✅ SKILL.md found."
else
    echo "❌ SKILL.md not found in skill directory."
    exit 1
fi

echo "🚀 dbt-transformation-patterns is ready."
exit 0
