#!/bin/bash
# Autogenerated health check by Agent Zero

echo "🔍 Validating memory-safety-patterns..."

# Check 1: Directory integrity
if [ -f "SKILL.md" ]; then
    echo "✅ SKILL.md located."
else
    echo "❌ SKILL.md missing!"
    exit 1
fi

# Check 2: Core Dependencies
echo "Checking dependencies..."

# Check for Rust compiler
if command -v rustc &> /dev/null; then
    echo "✅ Rust compiler (rustc) found."
else
    echo "⚠️  Rust compiler (rustc) not found. Install with: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
fi

# Check for C++ compiler
if command -v g++ &> /dev/null; then
    echo "✅ C++ compiler (g++) found."
else
    echo "⚠️  C++ compiler (g++) not found. Install with: apt-get install g++"
fi

# Check for C compiler
if command -v gcc &> /dev/null; then
    echo "✅ C compiler (gcc) found."
else
    echo "⚠️  C compiler (gcc) not found. Install with: apt-get install gcc"
fi

# Check for Valgrind
if command -v valgrind &> /dev/null; then
    echo "✅ Valgrind found."
else
    echo "⚠️  Valgrind not found. Install with: apt-get install valgrind"
fi

# Check for Cargo
if command -v cargo &> /dev/null; then
    echo "✅ Cargo found."
else
    echo "⚠️  Cargo not found. Install with Rust installation."
fi

echo "🚀 memory-safety-patterns is ready."
exit 0
