#!/bin/bash
# Autogenerated installation script by Agent Zero

echo "🔧 Installing dependencies for go-concurrency-patterns..."

# Check if Go is already installed
if command -v go &> /dev/null; then
    echo "✅ Go is already installed"
    echo "Go version: $(go version)"
    exit 0
fi

echo "📦 Installing Go..."

# Update package list and install Go
apt-get update && apt-get install -y golang-go

if command -v go &> /dev/null; then
    echo "✅ Go installed successfully"
    echo "Go version: $(go version)"
else
    echo "⚠️  Failed to install Go via apt-get. Trying alternative method..."
    echo "Please install Go manually from: https://go.dev/dl/"
    echo "Or run: curl -OL https://golang.org/dl/go1.21.0.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz"
    echo "Add to PATH: export PATH=$PATH:/usr/local/go/bin"
    exit 1
fi

echo "🚀 Go installation complete. You can now use go-concurrency-patterns skill."
