#!/bin/bash
# Autogenerated health check by Agent Zero

echo "🔍 Validating go-concurrency-patterns..."

# Check 1: Go installation
if command -v go &> /dev/null; then
    echo "✅ Go is installed: $(go version)"
else
    echo "❌ Go not found. Install with: apt-get install golang-go"
    echo "   or download from: https://go.dev/dl/"
    exit 1
fi

# Check 2: Basic Go functionality
echo "Testing basic Go compilation..."
cat > /tmp/test_go_concurrency.go << 'GOEOF'
package main

import (
    "fmt"
    "sync"
)

func main() {
    var wg sync.WaitGroup
    wg.Add(1)
    go func() {
        defer wg.Done()
        fmt.Println("Go concurrency test passed")
    }()
    wg.Wait()
}
GOEOF

if go run /tmp/test_go_concurrency.go 2>/dev/null; then
    echo "✅ Basic Go concurrency test passed"
    rm /tmp/test_go_concurrency.go
else
    echo "⚠️  Basic Go concurrency test failed"
    rm /tmp/test_go_concurrency.go
    exit 1
fi

echo "🚀 go-concurrency-patterns is ready."
exit 0
